---
title: "sample_counts"
author: "Lauren Kremer"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


pkgTest <- function(x)
{
  if (x %in% rownames(installed.packages()) == FALSE) {
    install.packages(x, dependencies= TRUE)
  }
  library(x, character.only = TRUE)
}

# Make a vector of the packages you need
neededPackages <- c('ggplot2', 'tidyverse', 'reshape2', 'lubridate', 'plotly', 'magrittr', 'scales', 'xtable') #tools for plot titles 

for (package in neededPackages){pkgTest(package)}

```

```{r importdata}
file_path <- "/Users/laurenkremer/Dropbox/Fraser Experimental Forest/Sample_inventory_chemistry_logs/NSFSampleLog_forR.csv"

cols <- c('watershed', 'location', 'position', 'type')

dat <- read.table(file_path, skip = 0, header = TRUE, sep = ",", row.names = NULL, as.is = TRUE) %>%
  separate(Label, c("watershed", "location", "position"), sep = "_")%>%
  mutate(date = mdy(Date)) %>% 
  select (date, watershed, location, position, LC.MS, FTICR.MS, Fluorescence, Respiration, DOC, IC, type, lat, long)

dat<- dat %<>% 
  mutate_at(cols, factor)

```

#Make a series of subsets for figures
```{r}
long <- melt(dat, id.vars = c("watershed", "location", "position", "date","type", "lat", "long")) %>% 
  filter(value != 0) %>% 
  filter(type != 'xtra_dh') %>%
  mutate(  ## add another column indicating whether sample is from stream or well. 
    type = if_else(
      # Determine which values in the column match the regex.
      grepl("stream", position, fixed = TRUE),
      # write any matches with stream; otherwise indicate as a well.
      'stream', 'well'
    )
  ) %>%
  mutate(
    type = if_else(
      # Determine which values in the column match the regex.
      grepl("flume", position, fixed = TRUE),
      # Overwrite any matches with flume; otherwise keep current value.
      'flume', type
    )
  )


long_ws <- long %>%
  filter(watershed != 'ssfp')

dat_dh <- subset(dat, dat$watershed == 'dh')

dat_fc <- subset(dat, dat$watershed == 'fc')

dat_lexen <- subset(dat, dat$watershed == 'lexen')

dat_ssfp <- subset(dat, dat$watershed == 'ssfp')
```

```{r}
# Generate summary tables

table1 <- long_ws %>%
  mutate(year = lubridate::year(date)) %>%
  select(-date) %>%
  group_by(watershed, location, type, variable, year) %>%
  summarize(count = sum(value)) %>%
  ungroup()

knitr::kable(table1[, 1:6], "simple")
```

```{r}
# Generate summary tables

table2 <- long_ws %>%
  mutate(year = lubridate::year(date)) %>%
  select(-date, year, variable) %>%
  group_by(watershed, location, type) %>%
  summarize(count = sum(value)) %>%
  ungroup()

knitr::kable(table2[, 1:4], "simple")
```

```{r}
# Generate summary tables

ICtable <- long_ws %>%
  filter(watershed == 'dh') %>%
  mutate(year = lubridate::year(date)) %>%
  select(-date, year, variable) %>%
  group_by(location, type, lat, long) %>%
  summarize(count = sum(value)) %>%
  ungroup()

knitr::kable(ICtable[, 1:5], "simple")

#file_path <- "/Users/laurenkremer/Dropbox/Fraser Experimental Forest/Interactive_map/sample_counts/DH_IC_counts.csv"

file_path <- "/Users/laurenkremer/Dropbox/Fraser Experimental Forest/Interactive_map/sample_counts/DH_counts.csv"
write.csv(ICtable, file = file_path)
```

```{r}

dhtable <- long_ws %>%
  filter(watershed == 'dh') 

ggp <- ggplot(dhtable, aes(date, fill = variable)) +
# Create ggplot2 histogram with default colors
  geom_histogram() +
  scale_x_date(date_breaks = "1 months", date_labels = "%b %y") +
  facet_wrap(~type, nrow = 3) +
  ylab('Sample count') +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(
  # Hide panel borders and remove grid lines
  #panel.border = element_blank(),
  panel.background = element_rect(fill = "white"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black")
  ) +
  guides(fill=guide_legend(title="Sample source"))
    
ggp

```





```{r}
ggp <- ggplot(long_ws, aes(date, fill = variable)) +
# Create ggplot2 histogram with default colors
  geom_histogram() +
  scale_x_date(date_breaks = "1 months", date_labels = "%b %y") +
  facet_wrap(~type, nrow = 3) +
  ylab('Sample count') +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(
  # Hide panel borders and remove grid lines
  #panel.border = element_blank(),
  panel.background = element_rect(fill = "white"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black")
  ) +
  guides(fill=guide_legend(title="Sample source"))
    
ggp
```


```{r}

dat_lexen <- dat_lexen[, c('location', 'FTICR.MS', 'date', 'position')]
ggp <- ggplot(dat_lexen, aes(date, fill = position)) +  # Create ggplot2 histogram with default colors
  geom_histogram() +
  ggtitle('Lexen') +
  facet_wrap(~location, nrow = 3) + #, scales = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 90))

#rgrid <- plot_grid(R.mean, R.max, R.range + theme(legend.position="none"),
#                 nrow = 3, rel_widths = c(1, 1), rel_heights = c(1/3.5, 1/3.9, 1/2.6))

ggp
```

```{r}
dat_fool <- dat_fc[, c('location', 'FTICR.MS', 'date', 'position')]
ggp <- ggplot(dat_fool, aes(date, fill = position)) +  # Create ggplot2 histogram with default colors
  geom_histogram() +
  ggtitle('Fool') +
  facet_wrap(~location, nrow = 3) + #, scales = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 90))

#rgrid <- plot_grid(R.mean, R.max, R.range + theme(legend.position="none"),
#                 nrow = 3, rel_widths = c(1, 1), rel_heights = c(1/3.5, 1/3.9, 1/2.6))

ggp
```

```{r}
dat_dh<- dat_dh[, c('location', 'FTICR.MS', 'date', 'position')]
ggp <- ggplot(dat_dh, aes(date, fill = position)) +  # Create ggplot2 histogram with default colors
  geom_histogram() +
  ggtitle('Deadhorse') +
  facet_wrap(~location, nrow = 3) +
    scale_fill_manual(values=c("#330033", "#990099", "#330099", "#6666FF", "#66CCFF")) +#, scales = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 90))

#rgrid <- plot_grid(R.mean, R.max, R.range + theme(legend.position="none"),
#                 nrow = 3, rel_widths = c(1, 1), rel_heights = c(1/3.5, 1/3.9, 1/2.6))

ggp
```

```{r}
dat_out <- subset(dat, dat$location == '1')
dat_out <- dat_out[, c('location', 'Respiration', 'date','type', 'position', 
                       'watershed')]
ggp <- ggplot(dat_out, aes(date, fill = watershed)) +  # Create ggplot2 histogram with default colors
  geom_histogram() +
  ggtitle('All Respiration samples from outlets') +
  scale_y_continuous(breaks = pretty_breaks())+
  facet_wrap(~position, nrow = 3) + #, scales = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 90))
ggp
```

```{r}
dat_out <- subset(dat, dat$location == '1')
dat_out <- dat_out[, c('location', 'FTICR.MS', 'date','type', 'position', 
                       'watershed')]
ggp <- ggplot(dat_out, aes(date, fill = watershed)) +  # Create ggplot2 histogram with default colors
  geom_histogram() +
  ggtitle('All FTICR.MS samples from outlets') +
  scale_y_continuous(breaks = pretty_breaks())+
  facet_wrap(~position, nrow = 3) + #, scales = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 90))
ggp
```

```{r}
dat_out <- subset(dat, dat$location == '1')
dat_out <- dat_out[, c('location', 'DOC', 'date','type', 'position', 
                       'watershed')]
ggp <- ggplot(dat_out, aes(date, fill = watershed)) +  # Create ggplot2 histogram with default colors
  geom_histogram() +
  ggtitle('All DOC samples from outlets') +
  scale_y_continuous(breaks = pretty_breaks())+
  facet_wrap(~position, nrow = 3) + #, scales = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 90))
ggp
```


```{r}
#library(raster)

#dh <- raster("/Users/laurenkremer/Dropbox/fraser_ef_kremer/layers/deadhorse_ndvi_clipped.tif")

#dh <-hist(dh)
```

```{r}
#r <- raster("/Users/laurenkremer/Dropbox/fraser_ef_kremer/layers/fool_ndvi_clipped.tif")

#r <-hist(r)
```


