---
title: "conductivity"
author: "Lauren Kremer"
date: "5/23/2022"
output: html_document
---

```{r}
source('./functions/co2_DO_functions.R') #load helper functions

# Make a vector of the packages you need
neededPackages <- c('tidyverse', 'lubridate', 'xts', 'dygraphs', 'ggrepel','knitr', 'plotly', 'reshape2') #tools for plot titles 

# For every package in the vector, apply your pkgTest function
for (package in neededPackages){pkgTest(package)}
```


```{r}
#Clean By Site

# open and concatenate CO2 data
opn_ssfp_cond_21 <- function(interfiles, year, location) {
  file_path <- paste(getwd(),interfiles, year,location, sep='/')
  path_list <- paste(file_path, list.files(file_path, recursive = TRUE), sep= '/') #recursive =T will also find files in nested directories
  data <- lapply(path_list, function(x) {
    dat <- read.table(x, skip = 1, header = TRUE, sep = ",", row.names = NULL, as.is = TRUE)
    # for each item in path list, grab identifying labels from file path
    dat$year <- unlist(strsplit(x, "/"))[9]
    dat$plottype <- unlist(strsplit(x, "/"))[11]
    dat$depth <- unlist(strsplit(unlist(strsplit(x, "/"))[12], '_'))[2]
    return(dat)
  })
  combined.data <- do.call(rbind, data)
  combined.data <- combined.data %>%
    mutate(datetime = lubridate::mdy_hm(datetime))%>%
    arrange(datetime)%>%
    distinct()%>%
   return(combined.data)
}
```


###Load data with opn_concat

```{r}
interfiles <- 'formatted_data/conductivity'
# possible locations: 'dh', 'est_louis', 'fool', 'lexen'
year <- '2021'
location <- 'ssfp'

condu_raw <- opn_ssfp_cond_21(interfiles, year, location) #%>% #add an ID column to identify problem points 
  #mutate(sample_year = year) #add a year column, this might be useful to something like a 
  #facet wrap to compare years across plots

# HOBO's range reporting will give two values for each time interval, find a mean of these to start:
condu_summ <- condu_raw %>%
  mutate(day = date(datetime)) %>%
  mutate(hour = hour(datetime)) %>%
  group_by(day, hour, year, plottype, depth) %>%
  summarise(mean_low = mean(low_range_uScm), mean_full = mean(full_range_uScm)) 
```


```{r}
#quick plot of summary data by hour

melt_condu_summ <- melt(condu_summ ,  id.vars = c('day','hour', 'year', 'plottype', 'depth'), variable.name =  'series')

ICplot <- ggplot(melt_condu_summ, aes(day, value)) +
  geom_line(aes(color = plottype)) +
  facet_wrap(vars(depth))

ICplot
```


```{r}
opn_ssfp_cond_22 <- function(interfiles, year, location) {
  file_path <- paste(getwd(),interfiles, year,location, sep='/')
  path_list <- paste(file_path, list.files(file_path, recursive = TRUE), sep= '/') #recursive =T will also find files in nested directories
  data <- lapply(path_list, function(x) {
    dat <- read.csv(x, skip = 0, header = TRUE, sep = ",", row.names = NULL, as.is = TRUE)
    dat <- dat[, 1:4]
    colnames(dat) <- c('ID', 'datetime', 'full_range_us', 'temp_c')
    # for each item in path list, grab identifying labels from file path
    dat$year <- unlist(strsplit(x, "/"))[9]
    dat$plottype <- unlist(strsplit(unlist(strsplit(x, "/"))[11], '_'))[1]
    dat$depth <- unlist(strsplit(unlist(strsplit(x, "/"))[11], '_'))[2]
    return(dat)
  })
  combined.data <- do.call(rbind, data)
  combined.data <- combined.data %>%
    mutate(datetime = lubridate::mdy_hm(datetime))%>%
    arrange(datetime)%>%
    distinct()%>%
   return(combined.data)
}
```

```{r}
interfiles <- 'formatted_data/conductivity'
# possible locations: 'dh', 'est_louis', 'fool', 'lexen'
year <- '2022'
location <- 'ssfp'

condu_raw <- opn_ssfp_cond(interfiles, year, location) #%>% #add an ID column to identify problem points 
  #mutate(sample_year = year) #add a year column, this might be useful to something like a 
  #facet wrap to compare years across plots

# HOBO's range reporting will give two values for each time interval, find a mean of these to start:
condu_summ <- condu_raw %>%
  mutate(day = date(datetime)) %>%
  mutate(hour = hour(datetime)) %>%
  group_by(day, hour, year, plottype, depth) %>%
  summarise(mean_low = mean(low_range_uScm), mean_full = mean(full_range_uScm)) 
```

