---
title: "visualize_chemistry"
author: "Lauren Kremer"
date: '2022-07-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pkgTest <- function(x)
{
  if (x %in% rownames(installed.packages()) == FALSE) {
    install.packages(x, dependencies= TRUE)
  }
  library(x, character.only = TRUE)
}

# Make a vector of the packages you need
neededPackages <- c('tidyverse', 'magrittr', 'lubridate', 'xts', 'dygraphs', 'ggrepel','knitr', 'plotly') #tools for plot titles 

# For every package in the vector, apply your pkgTest function
for (package in neededPackages){pkgTest(package)}

```

```{r}

filepath <- paste(getwd(), 'formatted_data', 'chemistry', sep = '/')
file_list <- paste(filepath, list.files(filepath, pattern = '*.csv'), sep= '/')

dat <- lapply(file_list, function(x) {
      dat <- read.table(x, skip = 0, header = TRUE, sep = ",", row.names = NULL, as.is = TRUE) 
      return(dat)
      }) 

cols <- c('watershed', 'location', 'position', 'type')

concat <- function(dat) {
  combined.data <- do.call(rbind, dat) #combine datasets as stacked rows
  combined.data <- combined.data %>%
    mutate(date = lubridate::mdy(date)) %>% 
    mutate(month = lubridate::month(ymd(date), label = TRUE)) %>%
    mutate(year = lubridate::year(date)) %>%
    separate(label, into = c('watershed', 'location', 'position'), sep = '_', remove = TRUE) %>%
    arrange(date) %>% 
    drop_na() %>%
    select(-c('time'))  %>% 
    mutate_at(cols, factor)
   return(combined.data)
}
  
chemdf <- concat(dat)

str(chemdf)
```

```{r}
ggplot(chemdf[chemdf$watershed != 'ssfp',], aes(x = month, y = DOC_mg_l, fill = watershed)) +
  geom_boxplot() +
  theme(axis.text = element_text(angle = 90))
```

```{r}
ggplot(chemdf[chemdf$watershed != 'ssfp',], aes(x = month, y = DOC_mg_l, fill = position)) +
  geom_boxplot() +
  theme(axis.text = element_text(angle = 90))

```

```{r}
ggplot(chemdf[chemdf$watershed != 'ssfp',], aes(x = date, y = DOC_mg_l, fill = position)) +
  geom_boxplot() +
  theme(axis.text = element_text(angle = 90))

```
